language: python
python:
  - "3.4"
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#ubuntu-solutions"
    use_notice: true
    skip_join: true
    on_failure: change
    on_success: never
install:
  - travis_retry pip install tox
script:
  - travis_retry tox
